DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
description VARCHAR(100) NOT NULL,
completed VARCHAR(50) NOT NULL,
createdate DATE
);